name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - dev-sakshi
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 3. Give Maven Wrapper permission
      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      # 4. Run tests
      - name: Run Tests
        run: ./mvnw test

      # 5. Build Spring Boot application
      - name: Build Application
        run: ./mvnw clean package -DskipTests

      # 6. Upload JAR as artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-application
          path: target/*.jar